/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables
 *
 * The version of the OpenAPI document: 0.69.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ContentKey } from './ContentKey';
import {
    ContentKeyFromJSON,
    ContentKeyFromJSONTyped,
    ContentKeyToJSON,
} from './ContentKey';

/**
 * 
 * @export
 * @interface AddedContent
 */
export interface AddedContent {
    /**
     * 
     * @type {ContentKey}
     * @memberof AddedContent
     */
    key: ContentKey;
}

/**
 * Check if a given object implements the AddedContent interface.
 */
export function instanceOfAddedContent(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;

    return isInstance;
}

export function AddedContentFromJSON(json: any): AddedContent {
    return AddedContentFromJSONTyped(json, false);
}

export function AddedContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddedContent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': ContentKeyFromJSON(json['key']),
    };
}

export function AddedContentToJSON(value?: AddedContent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': ContentKeyToJSON(value.key),
    };
}

