/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReferenceMetadata } from './ReferenceMetadata';
import {
    ReferenceMetadataFromJSON,
    ReferenceMetadataFromJSONTyped,
    ReferenceMetadataToJSON,
} from './ReferenceMetadata';

/**
 * 
 * @export
 * @interface Branch
 */
export interface Branch {
    /**
     * 
     * @type {string}
     * @memberof Branch
     */
    name: string;
    /**
     * 
     * @type {ReferenceMetadata}
     * @memberof Branch
     */
    metadata?: ReferenceMetadata;
    /**
     * 
     * @type {string}
     * @memberof Branch
     */
    hash?: string;
}

/**
 * Check if a given object implements the Branch interface.
 */
export function instanceOfBranch(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function BranchFromJSON(json: any): Branch {
    return BranchFromJSONTyped(json, false);
}

export function BranchFromJSONTyped(json: any, ignoreDiscriminator: boolean): Branch {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'metadata': !exists(json, 'metadata') ? undefined : ReferenceMetadataFromJSON(json['metadata']),
        'hash': !exists(json, 'hash') ? undefined : json['hash'],
    };
}

export function BranchToJSON(value?: Branch | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'metadata': ReferenceMetadataToJSON(value.metadata),
        'hash': value.hash,
    };
}

