/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReferenceMetadataV2 } from './ReferenceMetadataV2';
import {
    ReferenceMetadataV2FromJSON,
    ReferenceMetadataV2FromJSONTyped,
    ReferenceMetadataV2ToJSON,
} from './ReferenceMetadataV2';

/**
 * 
 * @export
 * @interface BranchV2
 */
export interface BranchV2 {
    /**
     * 
     * @type {string}
     * @memberof BranchV2
     */
    name: string;
    /**
     * 
     * @type {ReferenceMetadataV2}
     * @memberof BranchV2
     */
    metadata?: ReferenceMetadataV2;
    /**
     * 
     * @type {string}
     * @memberof BranchV2
     */
    hash?: string;
}

/**
 * Check if a given object implements the BranchV2 interface.
 */
export function instanceOfBranchV2(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function BranchV2FromJSON(json: any): BranchV2 {
    return BranchV2FromJSONTyped(json, false);
}

export function BranchV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): BranchV2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'metadata': !exists(json, 'metadata') ? undefined : ReferenceMetadataV2FromJSON(json['metadata']),
        'hash': !exists(json, 'hash') ? undefined : json['hash'],
    };
}

export function BranchV2ToJSON(value?: BranchV2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'metadata': ReferenceMetadataV2ToJSON(value.metadata),
        'hash': value.hash,
    };
}

