/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables
 *
 * The version of the OpenAPI document: 0.69.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ContentKeyV1 } from './ContentKeyV1';
import {
    ContentKeyV1FromJSON,
    ContentKeyV1FromJSONTyped,
    ContentKeyV1ToJSON,
} from './ContentKeyV1';
import type { ContentV1 } from './ContentV1';
import {
    ContentV1FromJSON,
    ContentV1FromJSONTyped,
    ContentV1ToJSON,
} from './ContentV1';

/**
 * 
 * @export
 * @interface ContentWithKeyV1
 */
export interface ContentWithKeyV1 {
    /**
     * 
     * @type {ContentKeyV1}
     * @memberof ContentWithKeyV1
     */
    key: ContentKeyV1;
    /**
     * 
     * @type {ContentV1}
     * @memberof ContentWithKeyV1
     */
    content: ContentV1;
}

/**
 * Check if a given object implements the ContentWithKeyV1 interface.
 */
export function instanceOfContentWithKeyV1(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "content" in value;

    return isInstance;
}

export function ContentWithKeyV1FromJSON(json: any): ContentWithKeyV1 {
    return ContentWithKeyV1FromJSONTyped(json, false);
}

export function ContentWithKeyV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentWithKeyV1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': ContentKeyV1FromJSON(json['key']),
        'content': ContentV1FromJSON(json['content']),
    };
}

export function ContentWithKeyV1ToJSON(value?: ContentWithKeyV1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': ContentKeyV1ToJSON(value.key),
        'content': ContentV1ToJSON(value.content),
    };
}

