/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContentKey
 */
export interface ContentKey {
    /**
     * 
     * @type {Array<string>}
     * @memberof ContentKey
     */
    elements: Array<string>;
}

/**
 * Check if a given object implements the ContentKey interface.
 */
export function instanceOfContentKey(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "elements" in value;

    return isInstance;
}

export function ContentKeyFromJSON(json: any): ContentKey {
    return ContentKeyFromJSONTyped(json, false);
}

export function ContentKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentKey {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'elements': json['elements'],
    };
}

export function ContentKeyToJSON(value?: ContentKey | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'elements': value.elements,
    };
}

