/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ContentV2 } from './ContentV2';
import {
    ContentV2FromJSON,
    ContentV2FromJSONTyped,
    ContentV2ToJSON,
} from './ContentV2';
import type { DocumentationV2 } from './DocumentationV2';
import {
    DocumentationV2FromJSON,
    DocumentationV2FromJSONTyped,
    DocumentationV2ToJSON,
} from './DocumentationV2';
import type { ReferenceV2 } from './ReferenceV2';
import {
    ReferenceV2FromJSON,
    ReferenceV2FromJSONTyped,
    ReferenceV2ToJSON,
} from './ReferenceV2';

/**
 * 
 * @export
 * @interface ContentResponseV2
 */
export interface ContentResponseV2 {
    /**
     * 
     * @type {ContentV2}
     * @memberof ContentResponseV2
     */
    content: ContentV2;
    /**
     * 
     * @type {ReferenceV2}
     * @memberof ContentResponseV2
     */
    effectiveReference?: ReferenceV2;
    /**
     * 
     * @type {DocumentationV2}
     * @memberof ContentResponseV2
     */
    documentation?: DocumentationV2;
}

/**
 * Check if a given object implements the ContentResponseV2 interface.
 */
export function instanceOfContentResponseV2(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "content" in value;

    return isInstance;
}

export function ContentResponseV2FromJSON(json: any): ContentResponseV2 {
    return ContentResponseV2FromJSONTyped(json, false);
}

export function ContentResponseV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentResponseV2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'content': ContentV2FromJSON(json['content']),
        'effectiveReference': !exists(json, 'effectiveReference') ? undefined : ReferenceV2FromJSON(json['effectiveReference']),
        'documentation': !exists(json, 'documentation') ? undefined : DocumentationV2FromJSON(json['documentation']),
    };
}

export function ContentResponseV2ToJSON(value?: ContentResponseV2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'content': ContentV2ToJSON(value.content),
        'effectiveReference': ReferenceV2ToJSON(value.effectiveReference),
        'documentation': DocumentationV2ToJSON(value.documentation),
    };
}

