/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables
 *
 * The version of the OpenAPI document: 0.69.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
} from './';

/**
 * 
 * @export
 * @interface ContentMetadata
 */
export interface ContentMetadata {
    /**
     * 
     * @type {string}
     * @memberof ContentMetadata
     */
    variant: string;
}

/**
 * Check if a given object implements the ContentMetadata interface.
 */
export function instanceOfContentMetadata(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "variant" in value;

    return isInstance;
}

export function ContentMetadataFromJSON(json: any): ContentMetadata {
    return ContentMetadataFromJSONTyped(json, false);
}

export function ContentMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentMetadata {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    if (!ignoreDiscriminator) {
    }
    return {
        
        'variant': json['variant'],
    };
}

export function ContentMetadataToJSON(value?: ContentMetadata | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'variant': value.variant,
    };
}

