/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DeltaLakeTable } from './DeltaLakeTable';
import {
    DeltaLakeTableFromJSON,
    DeltaLakeTableFromJSONTyped,
    DeltaLakeTableToJSON,
} from './DeltaLakeTable';
import type { IcebergTable } from './IcebergTable';
import {
    IcebergTableFromJSON,
    IcebergTableFromJSONTyped,
    IcebergTableToJSON,
} from './IcebergTable';
import type { IcebergView } from './IcebergView';
import {
    IcebergViewFromJSON,
    IcebergViewFromJSONTyped,
    IcebergViewToJSON,
} from './IcebergView';
import type { Namespace } from './Namespace';
import {
    NamespaceFromJSON,
    NamespaceFromJSONTyped,
    NamespaceToJSON,
} from './Namespace';
import type { UDF } from './UDF';
import {
    UDFFromJSON,
    UDFFromJSONTyped,
    UDFToJSON,
} from './UDF';

// import {
//      DeltaLakeTableFromJSONTyped,
//      IcebergTableFromJSONTyped,
//      IcebergViewFromJSONTyped,
//      NamespaceFromJSONTyped,
//      UDFFromJSONTyped
// } from './';

/**
 * 
 * @export
 * @interface Content
 */
export interface Content {
    /**
     * 
     * @type {string}
     * @memberof Content
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Content
     */
    metadataLocation?: string;
    /**
     * 
     * @type {number}
     * @memberof Content
     */
    snapshotId?: number;
    /**
     * 
     * @type {number}
     * @memberof Content
     */
    schemaId?: number;
    /**
     * 
     * @type {number}
     * @memberof Content
     */
    specId?: number;
    /**
     * 
     * @type {number}
     * @memberof Content
     */
    sortOrderId?: number;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof Content
     * @deprecated
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     * @type {Array<string>}
     * @memberof Content
     */
    metadataLocationHistory?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Content
     */
    checkpointLocationHistory?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Content
     */
    lastCheckpoint?: string;
    /**
     * 
     * @type {number}
     * @memberof Content
     */
    versionId?: number;
    /**
     * 
     * @type {string}
     * @memberof Content
     */
    sqlText?: string;
    /**
     * 
     * @type {string}
     * @memberof Content
     */
    dialect?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Content
     */
    elements?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof Content
     */
    properties?: { [key: string]: string; };
}

/**
 * Check if a given object implements the Content interface.
 */
export function instanceOfContent(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "metadataLocation" in value;
    isInstance = isInstance && "metadataLocationHistory" in value;
    isInstance = isInstance && "checkpointLocationHistory" in value;
    isInstance = isInstance && "sqlText" in value;
    isInstance = isInstance && "elements" in value;
    isInstance = isInstance && "properties" in value;

    return isInstance;
}

export function ContentFromJSON(json: any): Content {
    return ContentFromJSONTyped(json, false);
}

export function ContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Content {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    if (!ignoreDiscriminator) {
        if (json['type'] === 'DELTA_LAKE_TABLE') {
            return DeltaLakeTableFromJSONTyped(json, true);
        }
        if (json['type'] === 'ICEBERG_TABLE') {
            return IcebergTableFromJSONTyped(json, true);
        }
        if (json['type'] === 'ICEBERG_VIEW') {
            return IcebergViewFromJSONTyped(json, true);
        }
        if (json['type'] === 'NAMESPACE') {
            return NamespaceFromJSONTyped(json, true);
        }
        if (json['type'] === 'UDF') {
            return UDFFromJSONTyped(json, true);
        }
    }
    return {

        'id': !exists(json, 'id') ? undefined : json['id'],
        'metadataLocation': json['metadataLocation'],
        'snapshotId': !exists(json, 'snapshotId') ? undefined : json['snapshotId'],
        'schemaId': !exists(json, 'schemaId') ? undefined : json['schemaId'],
        'specId': !exists(json, 'specId') ? undefined : json['specId'],
        'sortOrderId': !exists(json, 'sortOrderId') ? undefined : json['sortOrderId'],
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
        'metadataLocationHistory': json['metadataLocationHistory'],
        'checkpointLocationHistory': json['checkpointLocationHistory'],
        'lastCheckpoint': !exists(json, 'lastCheckpoint') ? undefined : json['lastCheckpoint'],
        'versionId': !exists(json, 'versionId') ? undefined : json['versionId'],
        'sqlText': json['sqlText'],
        'dialect': !exists(json, 'dialect') ? undefined : json['dialect'],
        'elements': json['elements'],
        'properties': json['properties'],
    };
}

export function ContentToJSON(value?: Content | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'id': value.id,
        'metadataLocation': value.metadataLocation,
        'snapshotId': value.snapshotId,
        'schemaId': value.schemaId,
        'specId': value.specId,
        'sortOrderId': value.sortOrderId,
        'metadata': value.metadata,
        'metadataLocationHistory': value.metadataLocationHistory,
        'checkpointLocationHistory': value.checkpointLocationHistory,
        'lastCheckpoint': value.lastCheckpoint,
        'versionId': value.versionId,
        'sqlText': value.sqlText,
        'dialect': value.dialect,
        'elements': value.elements,
        'properties': value.properties,
    };
}

