/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ContentKeyV1 } from './ContentKeyV1';
import {
    ContentKeyV1FromJSON,
    ContentKeyV1FromJSONTyped,
    ContentKeyV1ToJSON,
} from './ContentKeyV1';
import type { MergeBehaviorV1 } from './MergeBehaviorV1';
import {
    MergeBehaviorV1FromJSON,
    MergeBehaviorV1FromJSONTyped,
    MergeBehaviorV1ToJSON,
} from './MergeBehaviorV1';

/**
 * 
 * @export
 * @interface ContentKeyDetailsV1
 */
export interface ContentKeyDetailsV1 {
    /**
     * 
     * @type {ContentKeyV1}
     * @memberof ContentKeyDetailsV1
     */
    key?: ContentKeyV1;
    /**
     * 
     * @type {MergeBehaviorV1}
     * @memberof ContentKeyDetailsV1
     */
    mergeBehavior?: MergeBehaviorV1;
}

/**
 * Check if a given object implements the ContentKeyDetailsV1 interface.
 */
export function instanceOfContentKeyDetailsV1(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ContentKeyDetailsV1FromJSON(json: any): ContentKeyDetailsV1 {
    return ContentKeyDetailsV1FromJSONTyped(json, false);
}

export function ContentKeyDetailsV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentKeyDetailsV1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': !exists(json, 'key') ? undefined : ContentKeyV1FromJSON(json['key']),
        'mergeBehavior': !exists(json, 'mergeBehavior') ? undefined : MergeBehaviorV1FromJSON(json['mergeBehavior']),
    };
}

export function ContentKeyDetailsV1ToJSON(value?: ContentKeyDetailsV1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': ContentKeyV1ToJSON(value.key),
        'mergeBehavior': MergeBehaviorV1ToJSON(value.mergeBehavior),
    };
}

