/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables
 *
 * The version of the OpenAPI document: 0.69.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ContentKeyV1 } from './ContentKeyV1';
import {
    ContentKeyV1FromJSON,
    ContentKeyV1FromJSONTyped,
    ContentKeyV1ToJSON,
} from './ContentKeyV1';

/**
 * Used to delete an existing content key.
 * 
 * If the key for a content shall change (aka a rename), then use a `Delete` operation using the current (old) key and a `Put` operation using the new key with the current `Content` in the the `value` field. See `Put` operation.
 * @export
 * @interface DeleteV1
 */
export interface DeleteV1 {
    /**
     * 
     * @type {ContentKeyV1}
     * @memberof DeleteV1
     */
    key: ContentKeyV1;
}

/**
 * Check if a given object implements the DeleteV1 interface.
 */
export function instanceOfDeleteV1(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;

    return isInstance;
}

export function DeleteV1FromJSON(json: any): DeleteV1 {
    return DeleteV1FromJSONTyped(json, false);
}

export function DeleteV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteV1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': ContentKeyV1FromJSON(json['key']),
    };
}

export function DeleteV1ToJSON(value?: DeleteV1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': ContentKeyV1ToJSON(value.key),
    };
}

