/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ContentKey } from './ContentKey';
import {
    ContentKeyFromJSON,
    ContentKeyFromJSONTyped,
    ContentKeyToJSON,
} from './ContentKey';

/**
 * Used to delete an existing content key.
 * 
 * If the key for a content shall change (aka a rename), then use a `Delete` operation using the current (old) key and a `Put` operation using the new key with the current `Content` in the the `value` field. See `Put` operation.
 * @export
 * @interface Delete
 */
export interface Delete {
    /**
     * 
     * @type {ContentKey}
     * @memberof Delete
     */
    key: ContentKey;
}

/**
 * Check if a given object implements the Delete interface.
 */
export function instanceOfDelete(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;

    return isInstance;
}

export function DeleteFromJSON(json: any): Delete {
    return DeleteFromJSONTyped(json, false);
}

export function DeleteFromJSONTyped(json: any, ignoreDiscriminator: boolean): Delete {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': ContentKeyFromJSON(json['key']),
    };
}

export function DeleteToJSON(value?: Delete | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': ContentKeyToJSON(value.key),
    };
}

