/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables
 *
 * The version of the OpenAPI document: 0.69.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeltaLakeTable
 */
export interface DeltaLakeTable {
    /**
     * 
     * @type {string}
     * @memberof DeltaLakeTable
     */
    id?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof DeltaLakeTable
     */
    metadataLocationHistory: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof DeltaLakeTable
     */
    checkpointLocationHistory: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof DeltaLakeTable
     */
    lastCheckpoint?: string;
}

/**
 * Check if a given object implements the DeltaLakeTable interface.
 */
export function instanceOfDeltaLakeTable(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "metadataLocationHistory" in value;
    isInstance = isInstance && "checkpointLocationHistory" in value;

    return isInstance;
}

export function DeltaLakeTableFromJSON(json: any): DeltaLakeTable {
    return DeltaLakeTableFromJSONTyped(json, false);
}

export function DeltaLakeTableFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeltaLakeTable {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'metadataLocationHistory': json['metadataLocationHistory'],
        'checkpointLocationHistory': json['checkpointLocationHistory'],
        'lastCheckpoint': !exists(json, 'lastCheckpoint') ? undefined : json['lastCheckpoint'],
    };
}

export function DeltaLakeTableToJSON(value?: DeltaLakeTable | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'metadataLocationHistory': value.metadataLocationHistory,
        'checkpointLocationHistory': value.checkpointLocationHistory,
        'lastCheckpoint': value.lastCheckpoint,
    };
}

