/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReferenceMetadataV1 } from './ReferenceMetadataV1';
import {
    ReferenceMetadataV1FromJSON,
    ReferenceMetadataV1FromJSONTyped,
    ReferenceMetadataV1ToJSON,
} from './ReferenceMetadataV1';

/**
 * 
 * @export
 * @interface DetachedV1
 */
export interface DetachedV1 {
    /**
     * 
     * @type {string}
     * @memberof DetachedV1
     */
    hash: string;
    /**
     * 
     * @type {ReferenceMetadataV1}
     * @memberof DetachedV1
     */
    metadata?: ReferenceMetadataV1;
}

/**
 * Check if a given object implements the DetachedV1 interface.
 */
export function instanceOfDetachedV1(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "hash" in value;

    return isInstance;
}

export function DetachedV1FromJSON(json: any): DetachedV1 {
    return DetachedV1FromJSONTyped(json, false);
}

export function DetachedV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): DetachedV1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hash': json['hash'],
        'metadata': !exists(json, 'metadata') ? undefined : ReferenceMetadataV1FromJSON(json['metadata']),
    };
}

export function DetachedV1ToJSON(value?: DetachedV1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hash': value.hash,
        'metadata': ReferenceMetadataV1ToJSON(value.metadata),
    };
}

