/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DiffEntryV1 } from './DiffEntryV1';
import {
    DiffEntryV1FromJSON,
    DiffEntryV1FromJSONTyped,
    DiffEntryV1ToJSON,
} from './DiffEntryV1';

/**
 * 
 * @export
 * @interface DiffResponseV1
 */
export interface DiffResponseV1 {
    /**
     * 
     * @type {boolean}
     * @memberof DiffResponseV1
     */
    hasMore?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DiffResponseV1
     */
    token?: string;
    /**
     * 
     * @type {Array<DiffEntryV1>}
     * @memberof DiffResponseV1
     */
    diffs?: Array<DiffEntryV1>;
}

/**
 * Check if a given object implements the DiffResponseV1 interface.
 */
export function instanceOfDiffResponseV1(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DiffResponseV1FromJSON(json: any): DiffResponseV1 {
    return DiffResponseV1FromJSONTyped(json, false);
}

export function DiffResponseV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): DiffResponseV1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hasMore': !exists(json, 'hasMore') ? undefined : json['hasMore'],
        'token': !exists(json, 'token') ? undefined : json['token'],
        'diffs': !exists(json, 'diffs') ? undefined : ((json['diffs'] as Array<any>).map(DiffEntryV1FromJSON)),
    };
}

export function DiffResponseV1ToJSON(value?: DiffResponseV1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hasMore': value.hasMore,
        'token': value.token,
        'diffs': value.diffs === undefined ? undefined : ((value.diffs as Array<any>).map(DiffEntryV1ToJSON)),
    };
}

