/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FetchOption = {
    Minimal: 'MINIMAL',
    All: 'ALL'
} as const;
export type FetchOption = typeof FetchOption[keyof typeof FetchOption];


export function FetchOptionFromJSON(json: any): FetchOption {
    return FetchOptionFromJSONTyped(json, false);
}

export function FetchOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): FetchOption {
    return json as FetchOption;
}

export function FetchOptionToJSON(value?: FetchOption | null): any {
    return value as any;
}

