/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReferenceCutoffPolicy } from './ReferenceCutoffPolicy';
import {
    ReferenceCutoffPolicyFromJSON,
    ReferenceCutoffPolicyFromJSONTyped,
    ReferenceCutoffPolicyToJSON,
} from './ReferenceCutoffPolicy';

/**
 * 
 * @export
 * @interface GarbageCollectorConfig
 */
export interface GarbageCollectorConfig {
    /**
     * The default cutoff policy.
     * Policies can be one of: - number of commits as an integer value - a duration (see java.time.Duration) - an ISO instant - 'NONE', means everything's considered as live
     * @type {string}
     * @memberof GarbageCollectorConfig
     */
    defaultCutoffPolicy?: string;
    /**
     * 
     * @type {Array<ReferenceCutoffPolicy>}
     * @memberof GarbageCollectorConfig
     */
    perRefCutoffPolicies?: Array<ReferenceCutoffPolicy>;
    /**
     * Files that have been created after 'gc-start-time - new-files-grace-period' are not being deleted.
     * @type {string}
     * @memberof GarbageCollectorConfig
     */
    newFilesGracePeriod?: string;
    /**
     * 
     * @type {number}
     * @memberof GarbageCollectorConfig
     */
    expectedFileCountPerContent?: number;
}

/**
 * Check if a given object implements the GarbageCollectorConfig interface.
 */
export function instanceOfGarbageCollectorConfig(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GarbageCollectorConfigFromJSON(json: any): GarbageCollectorConfig {
    return GarbageCollectorConfigFromJSONTyped(json, false);
}

export function GarbageCollectorConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): GarbageCollectorConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'defaultCutoffPolicy': !exists(json, 'defaultCutoffPolicy') ? undefined : json['defaultCutoffPolicy'],
        'perRefCutoffPolicies': !exists(json, 'perRefCutoffPolicies') ? undefined : ((json['perRefCutoffPolicies'] as Array<any>).map(ReferenceCutoffPolicyFromJSON)),
        'newFilesGracePeriod': !exists(json, 'newFilesGracePeriod') ? undefined : json['newFilesGracePeriod'],
        'expectedFileCountPerContent': !exists(json, 'expectedFileCountPerContent') ? undefined : json['expectedFileCountPerContent'],
    };
}

export function GarbageCollectorConfigToJSON(value?: GarbageCollectorConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'defaultCutoffPolicy': value.defaultCutoffPolicy,
        'perRefCutoffPolicies': value.perRefCutoffPolicies === undefined ? undefined : ((value.perRefCutoffPolicies as Array<any>).map(ReferenceCutoffPolicyToJSON)),
        'newFilesGracePeriod': value.newFilesGracePeriod,
        'expectedFileCountPerContent': value.expectedFileCountPerContent,
    };
}

