/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Represents the state of an Iceberg table in Nessie. An Iceberg table is globally identified via its unique 'Content.id'.
 * 
 * A Nessie commit-operation, performed via 'TreeApi.commitMultipleOperations',for Iceberg consists of a 'Operation.Put' with an 'IcebergTable' as in the 'content' field and the previous value of 'IcebergTable' in the 'expectedContent' field.
 * @export
 * @interface IcebergTableV2
 */
export interface IcebergTableV2 {
    /**
     * 
     * @type {string}
     * @memberof IcebergTableV2
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof IcebergTableV2
     */
    metadataLocation: string;
    /**
     * 
     * @type {number}
     * @memberof IcebergTableV2
     */
    snapshotId?: number;
    /**
     * 
     * @type {number}
     * @memberof IcebergTableV2
     */
    schemaId?: number;
    /**
     * 
     * @type {number}
     * @memberof IcebergTableV2
     */
    specId?: number;
    /**
     * 
     * @type {number}
     * @memberof IcebergTableV2
     */
    sortOrderId?: number;
}

/**
 * Check if a given object implements the IcebergTableV2 interface.
 */
export function instanceOfIcebergTableV2(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "metadataLocation" in value;

    return isInstance;
}

export function IcebergTableV2FromJSON(json: any): IcebergTableV2 {
    return IcebergTableV2FromJSONTyped(json, false);
}

export function IcebergTableV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): IcebergTableV2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'metadataLocation': json['metadataLocation'],
        'snapshotId': !exists(json, 'snapshotId') ? undefined : json['snapshotId'],
        'schemaId': !exists(json, 'schemaId') ? undefined : json['schemaId'],
        'specId': !exists(json, 'specId') ? undefined : json['specId'],
        'sortOrderId': !exists(json, 'sortOrderId') ? undefined : json['sortOrderId'],
    };
}

export function IcebergTableV2ToJSON(value?: IcebergTableV2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'metadataLocation': value.metadataLocation,
        'snapshotId': value.snapshotId,
        'schemaId': value.schemaId,
        'specId': value.specId,
        'sortOrderId': value.sortOrderId,
    };
}

