/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IcebergViewV1
 */
export interface IcebergViewV1 {
    /**
     * 
     * @type {string}
     * @memberof IcebergViewV1
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof IcebergViewV1
     */
    metadataLocation: string;
    /**
     * 
     * @type {number}
     * @memberof IcebergViewV1
     */
    versionId?: number;
    /**
     * 
     * @type {number}
     * @memberof IcebergViewV1
     */
    schemaId?: number;
    /**
     * 
     * @type {string}
     * @memberof IcebergViewV1
     */
    sqlText: string;
    /**
     * 
     * @type {string}
     * @memberof IcebergViewV1
     */
    dialect?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof IcebergViewV1
     * @deprecated
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the IcebergViewV1 interface.
 */
export function instanceOfIcebergViewV1(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "metadataLocation" in value;
    isInstance = isInstance && "sqlText" in value;

    return isInstance;
}

export function IcebergViewV1FromJSON(json: any): IcebergViewV1 {
    return IcebergViewV1FromJSONTyped(json, false);
}

export function IcebergViewV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): IcebergViewV1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'metadataLocation': json['metadataLocation'],
        'versionId': !exists(json, 'versionId') ? undefined : json['versionId'],
        'schemaId': !exists(json, 'schemaId') ? undefined : json['schemaId'],
        'sqlText': json['sqlText'],
        'dialect': !exists(json, 'dialect') ? undefined : json['dialect'],
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
    };
}

export function IcebergViewV1ToJSON(value?: IcebergViewV1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'metadataLocation': value.metadataLocation,
        'versionId': value.versionId,
        'schemaId': value.schemaId,
        'sqlText': value.sqlText,
        'dialect': value.dialect,
        'metadata': value.metadata,
    };
}

