/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables
 *
 * The version of the OpenAPI document: 0.69.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MergeBehaviorV2 = {
    Normal: 'NORMAL',
    Force: 'FORCE',
    Drop: 'DROP'
} as const;
export type MergeBehaviorV2 = typeof MergeBehaviorV2[keyof typeof MergeBehaviorV2];


export function MergeBehaviorV2FromJSON(json: any): MergeBehaviorV2 {
    return MergeBehaviorV2FromJSONTyped(json, false);
}

export function MergeBehaviorV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): MergeBehaviorV2 {
    return json as MergeBehaviorV2;
}

export function MergeBehaviorV2ToJSON(value?: MergeBehaviorV2 | null): any {
    return value as any;
}

