/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables
 *
 * The version of the OpenAPI document: 0.69.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MergeBehaviorV1 = {
    Normal: 'NORMAL',
    Force: 'FORCE',
    Drop: 'DROP'
} as const;
export type MergeBehaviorV1 = typeof MergeBehaviorV1[keyof typeof MergeBehaviorV1];


export function MergeBehaviorV1FromJSON(json: any): MergeBehaviorV1 {
    return MergeBehaviorV1FromJSONTyped(json, false);
}

export function MergeBehaviorV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): MergeBehaviorV1 {
    return json as MergeBehaviorV1;
}

export function MergeBehaviorV1ToJSON(value?: MergeBehaviorV1 | null): any {
    return value as any;
}

