/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MergeBehaviorV2 = {
    Normal: 'NORMAL',
    Force: 'FORCE',
    Drop: 'DROP'
} as const;
export type MergeBehaviorV2 = typeof MergeBehaviorV2[keyof typeof MergeBehaviorV2];


export function MergeBehaviorV2FromJSON(json: any): MergeBehaviorV2 {
    return MergeBehaviorV2FromJSONTyped(json, false);
}

export function MergeBehaviorV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): MergeBehaviorV2 {
    return json as MergeBehaviorV2;
}

export function MergeBehaviorV2ToJSON(value?: MergeBehaviorV2 | null): any {
    return value as any;
}

