/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables
 *
 * The version of the OpenAPI document: 0.69.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MergeBehavior = {
    Normal: 'NORMAL',
    Force: 'FORCE',
    Drop: 'DROP'
} as const;
export type MergeBehavior = typeof MergeBehavior[keyof typeof MergeBehavior];


export function MergeBehaviorFromJSON(json: any): MergeBehavior {
    return MergeBehaviorFromJSONTyped(json, false);
}

export function MergeBehaviorFromJSONTyped(json: any, ignoreDiscriminator: boolean): MergeBehavior {
    return json as MergeBehavior;
}

export function MergeBehaviorToJSON(value?: MergeBehavior | null): any {
    return value as any;
}

