/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables
 *
 * The version of the OpenAPI document: 0.69.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NamespaceUpdate
 */
export interface NamespaceUpdate {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof NamespaceUpdate
     */
    propertyUpdates?: { [key: string]: string; };
    /**
     * 
     * @type {Set<string>}
     * @memberof NamespaceUpdate
     */
    propertyRemovals?: Set<string>;
}

/**
 * Check if a given object implements the NamespaceUpdate interface.
 */
export function instanceOfNamespaceUpdate(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NamespaceUpdateFromJSON(json: any): NamespaceUpdate {
    return NamespaceUpdateFromJSONTyped(json, false);
}

export function NamespaceUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): NamespaceUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'propertyUpdates': !exists(json, 'propertyUpdates') ? undefined : json['propertyUpdates'],
        'propertyRemovals': !exists(json, 'propertyRemovals') ? undefined : json['propertyRemovals'],
    };
}

export function NamespaceUpdateToJSON(value?: NamespaceUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'propertyUpdates': value.propertyUpdates,
        'propertyRemovals': value.propertyRemovals === undefined ? undefined : Array.from(value.propertyRemovals as Set<any>),
    };
}

