/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables
 *
 * The version of the OpenAPI document: 0.69.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NamespaceV2
 */
export interface NamespaceV2 {
    /**
     * 
     * @type {string}
     * @memberof NamespaceV2
     */
    id?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof NamespaceV2
     */
    elements: Array<string>;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof NamespaceV2
     */
    properties: { [key: string]: string; };
}

/**
 * Check if a given object implements the NamespaceV2 interface.
 */
export function instanceOfNamespaceV2(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "elements" in value;
    isInstance = isInstance && "properties" in value;

    return isInstance;
}

export function NamespaceV2FromJSON(json: any): NamespaceV2 {
    return NamespaceV2FromJSONTyped(json, false);
}

export function NamespaceV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): NamespaceV2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'elements': json['elements'],
        'properties': json['properties'],
    };
}

export function NamespaceV2ToJSON(value?: NamespaceV2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'elements': value.elements,
        'properties': value.properties,
    };
}

