/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Configuration object to tell a client how a server is configured.
 * @export
 * @interface NessieConfigurationV2
 */
export interface NessieConfigurationV2 {
    /**
     * 
     * @type {string}
     * @memberof NessieConfigurationV2
     */
    defaultBranch?: string;
    /**
     * 
     * @type {number}
     * @memberof NessieConfigurationV2
     */
    minSupportedApiVersion?: number;
    /**
     * 
     * @type {number}
     * @memberof NessieConfigurationV2
     */
    maxSupportedApiVersion?: number;
    /**
     * 
     * @type {number}
     * @memberof NessieConfigurationV2
     */
    actualApiVersion?: number;
    /**
     * Semver version representing the behavior of the Nessie server.
     * 
     * Additional functionality might be added to Nessie servers within a "spec major version" in a non-breaking way. Clients are encouraged to check the spec version when using such added functionality.
     * @type {string}
     * @memberof NessieConfigurationV2
     */
    specVersion?: string;
    /**
     * 
     * @type {string}
     * @memberof NessieConfigurationV2
     */
    noAncestorHash?: string;
    /**
     * 
     * @type {Date}
     * @memberof NessieConfigurationV2
     */
    repositoryCreationTimestamp?: Date;
    /**
     * 
     * @type {Date}
     * @memberof NessieConfigurationV2
     */
    oldestPossibleCommitTimestamp?: Date;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof NessieConfigurationV2
     */
    additionalProperties?: { [key: string]: string; };
}

/**
 * Check if a given object implements the NessieConfigurationV2 interface.
 */
export function instanceOfNessieConfigurationV2(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NessieConfigurationV2FromJSON(json: any): NessieConfigurationV2 {
    return NessieConfigurationV2FromJSONTyped(json, false);
}

export function NessieConfigurationV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): NessieConfigurationV2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'defaultBranch': !exists(json, 'defaultBranch') ? undefined : json['defaultBranch'],
        'minSupportedApiVersion': !exists(json, 'minSupportedApiVersion') ? undefined : json['minSupportedApiVersion'],
        'maxSupportedApiVersion': !exists(json, 'maxSupportedApiVersion') ? undefined : json['maxSupportedApiVersion'],
        'actualApiVersion': !exists(json, 'actualApiVersion') ? undefined : json['actualApiVersion'],
        'specVersion': !exists(json, 'specVersion') ? undefined : json['specVersion'],
        'noAncestorHash': !exists(json, 'noAncestorHash') ? undefined : json['noAncestorHash'],
        'repositoryCreationTimestamp': !exists(json, 'repositoryCreationTimestamp') ? undefined : (new Date(json['repositoryCreationTimestamp'])),
        'oldestPossibleCommitTimestamp': !exists(json, 'oldestPossibleCommitTimestamp') ? undefined : (new Date(json['oldestPossibleCommitTimestamp'])),
        'additionalProperties': !exists(json, 'additionalProperties') ? undefined : json['additionalProperties'],
    };
}

export function NessieConfigurationV2ToJSON(value?: NessieConfigurationV2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'defaultBranch': value.defaultBranch,
        'minSupportedApiVersion': value.minSupportedApiVersion,
        'maxSupportedApiVersion': value.maxSupportedApiVersion,
        'actualApiVersion': value.actualApiVersion,
        'specVersion': value.specVersion,
        'noAncestorHash': value.noAncestorHash,
        'repositoryCreationTimestamp': value.repositoryCreationTimestamp === undefined ? undefined : (value.repositoryCreationTimestamp.toISOString()),
        'oldestPossibleCommitTimestamp': value.oldestPossibleCommitTimestamp === undefined ? undefined : (value.oldestPossibleCommitTimestamp.toISOString()),
        'additionalProperties': value.additionalProperties,
    };
}

