/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables
 *
 * The version of the OpenAPI document: 0.69.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Configuration object to tell a client how a server is configured.
 * @export
 * @interface NessieConfigurationV1
 */
export interface NessieConfigurationV1 {
    /**
     * 
     * @type {string}
     * @memberof NessieConfigurationV1
     */
    defaultBranch?: string;
    /**
     * 
     * @type {number}
     * @memberof NessieConfigurationV1
     */
    maxSupportedApiVersion?: number;
}

/**
 * Check if a given object implements the NessieConfigurationV1 interface.
 */
export function instanceOfNessieConfigurationV1(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NessieConfigurationV1FromJSON(json: any): NessieConfigurationV1 {
    return NessieConfigurationV1FromJSONTyped(json, false);
}

export function NessieConfigurationV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): NessieConfigurationV1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'defaultBranch': !exists(json, 'defaultBranch') ? undefined : json['defaultBranch'],
        'maxSupportedApiVersion': !exists(json, 'maxSupportedApiVersion') ? undefined : json['maxSupportedApiVersion'],
    };
}

export function NessieConfigurationV1ToJSON(value?: NessieConfigurationV1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'defaultBranch': value.defaultBranch,
        'maxSupportedApiVersion': value.maxSupportedApiVersion,
    };
}

