/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables
 *
 * The version of the OpenAPI document: 0.69.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CommitMeta } from './CommitMeta';
import {
    CommitMetaFromJSON,
    CommitMetaFromJSONTyped,
    CommitMetaToJSON,
} from './CommitMeta';
import type { Operation } from './Operation';
import {
    OperationFromJSON,
    OperationFromJSONTyped,
    OperationToJSON,
} from './Operation';

/**
 * 
 * @export
 * @interface Operations
 */
export interface Operations {
    /**
     * 
     * @type {CommitMeta}
     * @memberof Operations
     */
    commitMeta: CommitMeta;
    /**
     * 
     * @type {Array<Operation>}
     * @memberof Operations
     */
    operations: Array<Operation>;
}

/**
 * Check if a given object implements the Operations interface.
 */
export function instanceOfOperations(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "commitMeta" in value;
    isInstance = isInstance && "operations" in value;

    return isInstance;
}

export function OperationsFromJSON(json: any): Operations {
    return OperationsFromJSONTyped(json, false);
}

export function OperationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Operations {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'commitMeta': CommitMetaFromJSON(json['commitMeta']),
        'operations': ((json['operations'] as Array<any>).map(OperationFromJSON)),
    };
}

export function OperationsToJSON(value?: Operations | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'commitMeta': CommitMetaToJSON(value.commitMeta),
        'operations': ((value.operations as Array<any>).map(OperationToJSON)),
    };
}

