/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Content } from './Content';
import {
    ContentFromJSON,
    ContentFromJSONTyped,
    ContentToJSON,
} from './Content';

/**
 * 
 * @export
 * @interface PutExpectedContent
 */
export interface PutExpectedContent extends Content {
}

/**
 * Check if a given object implements the PutExpectedContent interface.
 */
export function instanceOfPutExpectedContent(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PutExpectedContentFromJSON(json: any): PutExpectedContent {
    return PutExpectedContentFromJSONTyped(json, false);
}

export function PutExpectedContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutExpectedContent {
    return json;
}

export function PutExpectedContentToJSON(value?: PutExpectedContent | null): any {
    return value;
}

