/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ContentV1 } from './ContentV1';
import {
    ContentV1FromJSON,
    ContentV1FromJSONTyped,
    ContentV1ToJSON,
} from './ContentV1';

/**
 * 
 * @export
 * @interface PutV1ExpectedContent
 */
export interface PutV1ExpectedContent extends ContentV1 {
}

/**
 * Check if a given object implements the PutV1ExpectedContent interface.
 */
export function instanceOfPutV1ExpectedContent(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PutV1ExpectedContentFromJSON(json: any): PutV1ExpectedContent {
    return PutV1ExpectedContentFromJSONTyped(json, false);
}

export function PutV1ExpectedContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutV1ExpectedContent {
    return json;
}

export function PutV1ExpectedContentToJSON(value?: PutV1ExpectedContent | null): any {
    return value;
}

