/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CommitMetaV2 } from './CommitMetaV2';
import {
    CommitMetaV2FromJSON,
    CommitMetaV2FromJSONTyped,
    CommitMetaV2ToJSON,
} from './CommitMetaV2';

/**
 * Only returned by the server when explicitly requested by the client and contains the following information:
 * 
 * - numCommitsAhead (number of commits ahead of the default branch)
 * 
 * - numCommitsBehind (number of commits behind the default branch)
 * 
 * - commitMetaOfHEAD (the commit metadata of the HEAD commit)
 * 
 * - commonAncestorHash (the hash of the common ancestor in relation to the default branch).
 * 
 * - numTotalCommits (the total number of commits in this reference).
 * @export
 * @interface ReferenceMetadataV2
 */
export interface ReferenceMetadataV2 {
    /**
     * 
     * @type {number}
     * @memberof ReferenceMetadataV2
     */
    numCommitsAhead?: number;
    /**
     * 
     * @type {number}
     * @memberof ReferenceMetadataV2
     */
    numCommitsBehind?: number;
    /**
     * 
     * @type {CommitMetaV2}
     * @memberof ReferenceMetadataV2
     */
    commitMetaOfHEAD?: CommitMetaV2;
    /**
     * 
     * @type {string}
     * @memberof ReferenceMetadataV2
     */
    commonAncestorHash?: string;
    /**
     * 
     * @type {number}
     * @memberof ReferenceMetadataV2
     */
    numTotalCommits?: number;
}

/**
 * Check if a given object implements the ReferenceMetadataV2 interface.
 */
export function instanceOfReferenceMetadataV2(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReferenceMetadataV2FromJSON(json: any): ReferenceMetadataV2 {
    return ReferenceMetadataV2FromJSONTyped(json, false);
}

export function ReferenceMetadataV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferenceMetadataV2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'numCommitsAhead': !exists(json, 'numCommitsAhead') ? undefined : json['numCommitsAhead'],
        'numCommitsBehind': !exists(json, 'numCommitsBehind') ? undefined : json['numCommitsBehind'],
        'commitMetaOfHEAD': !exists(json, 'commitMetaOfHEAD') ? undefined : CommitMetaV2FromJSON(json['commitMetaOfHEAD']),
        'commonAncestorHash': !exists(json, 'commonAncestorHash') ? undefined : json['commonAncestorHash'],
        'numTotalCommits': !exists(json, 'numTotalCommits') ? undefined : json['numTotalCommits'],
    };
}

export function ReferenceMetadataV2ToJSON(value?: ReferenceMetadataV2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'numCommitsAhead': value.numCommitsAhead,
        'numCommitsBehind': value.numCommitsBehind,
        'commitMetaOfHEAD': CommitMetaV2ToJSON(value.commitMetaOfHEAD),
        'commonAncestorHash': value.commonAncestorHash,
        'numTotalCommits': value.numTotalCommits,
    };
}

