/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables
 *
 * The version of the OpenAPI document: 0.69.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReferenceV1 } from './ReferenceV1';
import {
    ReferenceV1FromJSON,
    ReferenceV1FromJSONTyped,
    ReferenceV1ToJSON,
} from './ReferenceV1';

/**
 * 
 * @export
 * @interface ReferencesResponseV1
 */
export interface ReferencesResponseV1 {
    /**
     * 
     * @type {boolean}
     * @memberof ReferencesResponseV1
     */
    hasMore?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ReferencesResponseV1
     */
    token?: string;
    /**
     * 
     * @type {Array<ReferenceV1>}
     * @memberof ReferencesResponseV1
     */
    references: Array<ReferenceV1>;
}

/**
 * Check if a given object implements the ReferencesResponseV1 interface.
 */
export function instanceOfReferencesResponseV1(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "references" in value;

    return isInstance;
}

export function ReferencesResponseV1FromJSON(json: any): ReferencesResponseV1 {
    return ReferencesResponseV1FromJSONTyped(json, false);
}

export function ReferencesResponseV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferencesResponseV1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hasMore': !exists(json, 'hasMore') ? undefined : json['hasMore'],
        'token': !exists(json, 'token') ? undefined : json['token'],
        'references': ((json['references'] as Array<any>).map(ReferenceV1FromJSON)),
    };
}

export function ReferencesResponseV1ToJSON(value?: ReferencesResponseV1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hasMore': value.hasMore,
        'token': value.token,
        'references': ((value.references as Array<any>).map(ReferenceV1ToJSON)),
    };
}

