/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables
 *
 * The version of the OpenAPI document: 0.69.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CommitMeta } from './CommitMeta';
import {
    CommitMetaFromJSON,
    CommitMetaFromJSONTyped,
    CommitMetaToJSON,
} from './CommitMeta';

/**
 * Only returned by the server when explicitly requested by the client and contains the following information:
 * 
 * - numCommitsAhead (number of commits ahead of the default branch)
 * 
 * - numCommitsBehind (number of commits behind the default branch)
 * 
 * - commitMetaOfHEAD (the commit metadata of the HEAD commit)
 * 
 * - commonAncestorHash (the hash of the common ancestor in relation to the default branch).
 * 
 * - numTotalCommits (the total number of commits in this reference).
 * @export
 * @interface ReferenceMetadata
 */
export interface ReferenceMetadata {
    /**
     * 
     * @type {number}
     * @memberof ReferenceMetadata
     */
    numCommitsAhead?: number;
    /**
     * 
     * @type {number}
     * @memberof ReferenceMetadata
     */
    numCommitsBehind?: number;
    /**
     * 
     * @type {CommitMeta}
     * @memberof ReferenceMetadata
     */
    commitMetaOfHEAD?: CommitMeta;
    /**
     * 
     * @type {string}
     * @memberof ReferenceMetadata
     */
    commonAncestorHash?: string;
    /**
     * 
     * @type {number}
     * @memberof ReferenceMetadata
     */
    numTotalCommits?: number;
}

/**
 * Check if a given object implements the ReferenceMetadata interface.
 */
export function instanceOfReferenceMetadata(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReferenceMetadataFromJSON(json: any): ReferenceMetadata {
    return ReferenceMetadataFromJSONTyped(json, false);
}

export function ReferenceMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferenceMetadata {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'numCommitsAhead': !exists(json, 'numCommitsAhead') ? undefined : json['numCommitsAhead'],
        'numCommitsBehind': !exists(json, 'numCommitsBehind') ? undefined : json['numCommitsBehind'],
        'commitMetaOfHEAD': !exists(json, 'commitMetaOfHEAD') ? undefined : CommitMetaFromJSON(json['commitMetaOfHEAD']),
        'commonAncestorHash': !exists(json, 'commonAncestorHash') ? undefined : json['commonAncestorHash'],
        'numTotalCommits': !exists(json, 'numTotalCommits') ? undefined : json['numTotalCommits'],
    };
}

export function ReferenceMetadataToJSON(value?: ReferenceMetadata | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'numCommitsAhead': value.numCommitsAhead,
        'numCommitsBehind': value.numCommitsBehind,
        'commitMetaOfHEAD': CommitMetaToJSON(value.commitMetaOfHEAD),
        'commonAncestorHash': value.commonAncestorHash,
        'numTotalCommits': value.numTotalCommits,
    };
}

