/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables
 *
 * The version of the OpenAPI document: 0.69.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Reference } from './Reference';
import {
    ReferenceFromJSON,
    ReferenceFromJSONTyped,
    ReferenceToJSON,
} from './Reference';

/**
 * 
 * @export
 * @interface SingleReferenceResponse
 */
export interface SingleReferenceResponse {
    /**
     * 
     * @type {Reference}
     * @memberof SingleReferenceResponse
     */
    reference: Reference;
}

/**
 * Check if a given object implements the SingleReferenceResponse interface.
 */
export function instanceOfSingleReferenceResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "reference" in value;

    return isInstance;
}

export function SingleReferenceResponseFromJSON(json: any): SingleReferenceResponse {
    return SingleReferenceResponseFromJSONTyped(json, false);
}

export function SingleReferenceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SingleReferenceResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reference': ReferenceFromJSON(json['reference']),
    };
}

export function SingleReferenceResponseToJSON(value?: SingleReferenceResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reference': ReferenceToJSON(value.reference),
    };
}

