/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables
 *
 * The version of the OpenAPI document: 0.69.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReferenceMetadata } from './ReferenceMetadata';
import {
    ReferenceMetadataFromJSON,
    ReferenceMetadataFromJSONTyped,
    ReferenceMetadataToJSON,
} from './ReferenceMetadata';

/**
 * 
 * @export
 * @interface Tag
 */
export interface Tag {
    /**
     * 
     * @type {string}
     * @memberof Tag
     */
    name: string;
    /**
     * 
     * @type {ReferenceMetadata}
     * @memberof Tag
     */
    metadata?: ReferenceMetadata;
    /**
     * 
     * @type {string}
     * @memberof Tag
     */
    hash?: string;
}

/**
 * Check if a given object implements the Tag interface.
 */
export function instanceOfTag(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function TagFromJSON(json: any): Tag {
    return TagFromJSONTyped(json, false);
}

export function TagFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tag {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'metadata': !exists(json, 'metadata') ? undefined : ReferenceMetadataFromJSON(json['metadata']),
        'hash': !exists(json, 'hash') ? undefined : json['hash'],
    };
}

export function TagToJSON(value?: Tag | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'metadata': ReferenceMetadataToJSON(value.metadata),
        'hash': value.hash,
    };
}

