/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * When a repository configuration for the same type as in the request object did not exist, the response object will be null. Otherwise, if the configuration was updated, the old value will be returned.
 * @export
 * @interface ThePreviousStateOfTheRepositoryConfigurationObject
 */
export interface ThePreviousStateOfTheRepositoryConfigurationObject {
    /**
     * 
     * @type {ThePreviousStateOfTheRepositoryConfigurationObject}
     * @memberof ThePreviousStateOfTheRepositoryConfigurationObject
     */
    previous?: ThePreviousStateOfTheRepositoryConfigurationObject;
}

/**
 * Check if a given object implements the ThePreviousStateOfTheRepositoryConfigurationObject interface.
 */
export function instanceOfThePreviousStateOfTheRepositoryConfigurationObject(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ThePreviousStateOfTheRepositoryConfigurationObjectFromJSON(json: any): ThePreviousStateOfTheRepositoryConfigurationObject {
    return ThePreviousStateOfTheRepositoryConfigurationObjectFromJSONTyped(json, false);
}

export function ThePreviousStateOfTheRepositoryConfigurationObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThePreviousStateOfTheRepositoryConfigurationObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'previous': !exists(json, 'previous') ? undefined : ThePreviousStateOfTheRepositoryConfigurationObjectFromJSON(json['previous']),
    };
}

export function ThePreviousStateOfTheRepositoryConfigurationObjectToJSON(value?: ThePreviousStateOfTheRepositoryConfigurationObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'previous': ThePreviousStateOfTheRepositoryConfigurationObjectToJSON(value.previous),
    };
}

