/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables
 *
 * The version of the OpenAPI document: 0.69.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MergeBehavior } from './MergeBehavior';
import {
    MergeBehaviorFromJSON,
    MergeBehaviorFromJSONTyped,
    MergeBehaviorToJSON,
} from './MergeBehavior';
import type { MergeKeyBehavior } from './MergeKeyBehavior';
import {
    MergeKeyBehaviorFromJSON,
    MergeKeyBehaviorFromJSONTyped,
    MergeKeyBehaviorToJSON,
} from './MergeKeyBehavior';

/**
 * 
 * @export
 * @interface Transplant
 */
export interface Transplant {
    /**
     * Commit message for this transplant request.
     * @type {string}
     * @memberof Transplant
     */
    message?: string;
    /**
     * Lists the hashes of commits that should be transplanted into the target branch.
     * @type {Set<string>}
     * @memberof Transplant
     */
    hashesToTransplant: Set<string>;
    /**
     * The name of the reference that contains the 'source' commits for the requested merge or transplant operation.
     * @type {string}
     * @memberof Transplant
     */
    fromRefName: string;
    /**
     * Specific merge behaviour requests by content key.
     * 
     * The default is set by the `defaultKeyMergeMode` parameter.
     * @type {Array<MergeKeyBehavior>}
     * @memberof Transplant
     */
    keyMergeModes?: Array<MergeKeyBehavior>;
    /**
     * 
     * @type {MergeBehavior}
     * @memberof Transplant
     */
    defaultKeyMergeMode?: MergeBehavior;
    /**
     * When set to 'true' instructs the server to validate the request but to avoid committing any changes.
     * @type {boolean}
     * @memberof Transplant
     */
    dryRun?: boolean;
    /**
     * Whether to provide optional response data.
     * @type {boolean}
     * @memberof Transplant
     */
    fetchAdditionalInfo?: boolean;
    /**
     * When set to 'true' instructs the server to produce normal (non-error) responses in case a conflict is detected and report conflict details in the response payload.
     * @type {boolean}
     * @memberof Transplant
     */
    returnConflictAsResult?: boolean;
}

/**
 * Check if a given object implements the Transplant interface.
 */
export function instanceOfTransplant(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "hashesToTransplant" in value;
    isInstance = isInstance && "fromRefName" in value;

    return isInstance;
}

export function TransplantFromJSON(json: any): Transplant {
    return TransplantFromJSONTyped(json, false);
}

export function TransplantFromJSONTyped(json: any, ignoreDiscriminator: boolean): Transplant {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
        'hashesToTransplant': json['hashesToTransplant'],
        'fromRefName': json['fromRefName'],
        'keyMergeModes': !exists(json, 'keyMergeModes') ? undefined : ((json['keyMergeModes'] as Array<any>).map(MergeKeyBehaviorFromJSON)),
        'defaultKeyMergeMode': !exists(json, 'defaultKeyMergeMode') ? undefined : MergeBehaviorFromJSON(json['defaultKeyMergeMode']),
        'dryRun': !exists(json, 'dryRun') ? undefined : json['dryRun'],
        'fetchAdditionalInfo': !exists(json, 'fetchAdditionalInfo') ? undefined : json['fetchAdditionalInfo'],
        'returnConflictAsResult': !exists(json, 'returnConflictAsResult') ? undefined : json['returnConflictAsResult'],
    };
}

export function TransplantToJSON(value?: Transplant | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'hashesToTransplant': Array.from(value.hashesToTransplant as Set<any>),
        'fromRefName': value.fromRefName,
        'keyMergeModes': value.keyMergeModes === undefined ? undefined : ((value.keyMergeModes as Array<any>).map(MergeKeyBehaviorToJSON)),
        'defaultKeyMergeMode': MergeBehaviorToJSON(value.defaultKeyMergeMode),
        'dryRun': value.dryRun,
        'fetchAdditionalInfo': value.fetchAdditionalInfo,
        'returnConflictAsResult': value.returnConflictAsResult,
    };
}

