/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * Transactional Catalog for Data Lakes  * Git-inspired data version control * Cross-table transactions and visibility * Works with Apache Iceberg tables
 *
 * The version of the OpenAPI document: 0.69.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UDFV1
 */
export interface UDFV1 {
    /**
     * 
     * @type {string}
     * @memberof UDFV1
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UDFV1
     */
    sqlText: string;
    /**
     * 
     * @type {string}
     * @memberof UDFV1
     */
    dialect?: string;
}

/**
 * Check if a given object implements the UDFV1 interface.
 */
export function instanceOfUDFV1(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "sqlText" in value;

    return isInstance;
}

export function UDFV1FromJSON(json: any): UDFV1 {
    return UDFV1FromJSONTyped(json, false);
}

export function UDFV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): UDFV1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'sqlText': json['sqlText'],
        'dialect': !exists(json, 'dialect') ? undefined : json['dialect'],
    };
}

export function UDFV1ToJSON(value?: UDFV1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'sqlText': value.sqlText,
        'dialect': value.dialect,
    };
}

