/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ContentKeyV1 } from './ContentKeyV1';
import {
    ContentKeyV1FromJSON,
    ContentKeyV1FromJSONTyped,
    ContentKeyV1ToJSON,
} from './ContentKeyV1';

/**
 * 
 * @export
 * @interface UnchangedV1
 */
export interface UnchangedV1 {
    /**
     * 
     * @type {ContentKeyV1}
     * @memberof UnchangedV1
     */
    key: ContentKeyV1;
}

/**
 * Check if a given object implements the UnchangedV1 interface.
 */
export function instanceOfUnchangedV1(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;

    return isInstance;
}

export function UnchangedV1FromJSON(json: any): UnchangedV1 {
    return UnchangedV1FromJSONTyped(json, false);
}

export function UnchangedV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): UnchangedV1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': ContentKeyV1FromJSON(json['key']),
    };
}

export function UnchangedV1ToJSON(value?: UnchangedV1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': ContentKeyV1ToJSON(value.key),
    };
}

