/* tslint:disable */
/* eslint-disable */
/**
 * Nessie API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.65.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ContentKey } from './ContentKey';
import {
    ContentKeyFromJSON,
    ContentKeyFromJSONTyped,
    ContentKeyToJSON,
} from './ContentKey';

/**
 * 
 * @export
 * @interface Unchanged
 */
export interface Unchanged {
    /**
     * 
     * @type {ContentKey}
     * @memberof Unchanged
     */
    key: ContentKey;
}

/**
 * Check if a given object implements the Unchanged interface.
 */
export function instanceOfUnchanged(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;

    return isInstance;
}

export function UnchangedFromJSON(json: any): Unchanged {
    return UnchangedFromJSONTyped(json, false);
}

export function UnchangedFromJSONTyped(json: any, ignoreDiscriminator: boolean): Unchanged {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': ContentKeyFromJSON(json['key']),
    };
}

export function UnchangedToJSON(value?: Unchanged | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': ContentKeyToJSON(value.key),
    };
}

